document.writeln("<!--在线客服  -->");
document.writeln("<div class=\'scrollsidebar\' id=\'scrollsidebar\'>");
document.writeln("    <div class=\'side_content\'>");
document.writeln("        <div class=\'side_list\'>");
document.writeln("            <div class=\'side_title\'><a title=\'隐藏\' class=\'close_btn\'><span>关闭</span></a></div>");
document.writeln("            <div class=\'side_center\'>");
document.writeln("                <div class=\'other\'>");
document.writeln("                    <p><img src=\'images/qrcode.png\' width=\'80\' /></p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'side_bottom\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'show_btn\'><span>在线客服</span></div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<!-- 顶部 -->");
document.writeln("<link rel=\'stylesheet\' href=\'css/font-awesome.min.css?ver=1\' />");
document.writeln("<link rel=\'stylesheet\' href=\'css/public.min.css?ver=20190108\' />");
document.writeln("");
document.writeln("<!-- 头部 -->");
document.writeln("<div class=\'header\'>");
document.writeln("    <!-- 定义头部脱离文档流 -->");
document.writeln("    <div class=\'headerbg\'>");
document.writeln("        <!-- 头部左侧 -->");
document.writeln("        <div class=\'header_left\'>");
document.writeln("            <!-- logo -->");
document.writeln("            <div class=\'header_Logo\'>");
document.writeln("                <a><img src=\'images/2.png\' alt=\'\'></a>");
document.writeln("            </div>");
document.writeln("            <!-- 左侧通知 -->");
document.writeln("            <div class=\'header_News\'>");
document.writeln("                <ul>");
document.writeln("                    <!--系统通知内容区-->");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<link rel=\'stylesheet\' href=\'css/index.min.css\' />");
document.writeln("<style>");
document.writeln("    body {");
document.writeln("        overflow: auto;");
document.writeln("    }");
document.writeln("</style>");
document.writeln("");
document.writeln("<!-- 主体内容部分 -->");
document.writeln("<section class=\'toolsBody\'>");
document.writeln("    <section class=\'toolsBg\'>");
document.writeln("");
document.writeln("        <!-- 左侧导航菜单 -->");
document.writeln("        <div class=\'toolsLeft\'>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/index.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu  tabMenu0 toolsLeftMenuColor\'>新媒体助手大全</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'https://mp.weixin.qq.com/s/mBDJqQJN2NX0FAKpyjOTxA\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu2\'>入驻留言板</div>");
document.writeln("            </a>");
document.writeln("            <div class=\'toolsLeftMenu tabMenu2 toolsLeftMenuColor\'>新建留言板</div>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/attention.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu2\'>一键关注</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/short.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu3\'>短网址</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/hyperlink.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu4\'>微信超链接</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/video.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu1\'>微信视频提取</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/music.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu6\'>音乐/音频提取</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/background.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu8\'>微信背景图提取</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/cover.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu5\'>微信封面图提取</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/change.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu tabMenu7\'>临时转永久链接</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/ysdm.html\' target=\'_blank\'>");
document.writeln("                <div class=\'toolsLeftMenu\'>颜色代码</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/sucai.html\' target=\'_blank\' style=\'color: #2D2D2d\'>");
document.writeln("                <div class=\'toolsLeftMenu\'>热搜图文</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'https://wj.qq.com\' target=\'_blank\' style=\'color: #2D2D2d\'>");
document.writeln("                <div class=\'toolsLeftMenu\'>问卷调查</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://image.baidu.com\' target=\'_blank\' style=\'color: #2D2D2d\'>");
document.writeln("                <div class=\'toolsLeftMenu\'>百度搜图</div>");
document.writeln("            </a>");
document.writeln("            <a href=\'http://www.xmyeditor.com/tools/xiuxiu.html\' target=\'_blank\' style=\'color: #2D2D2d\'>");
document.writeln("                <div class=\'toolsLeftMenu\'>在线美图</div>");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <!-- 右侧内容 -->");
document.writeln("        <div class=\'toolsRight\'>");
document.writeln("");
document.writeln("            <!-- 小蚂蚁微信短网址工具 -->");
document.writeln("            <div class=\'toolsRightBg tabBg3\'>");
document.writeln("                <div class=\'toolsRightTitle\'>订阅号留言板小程序高级版（建议按Ctrl+D收藏该网页）</div>");
document.writeln("");
document.writeln("                <div class=\'notice\'>");
document.writeln("                    <ul>");
document.writeln("                        <li>原订阅号留言板暂时弃用，具体操作请查看最新使用视频。</li>");
document.writeln("                        <li>2019-08-20号公众号更新，导致访问小程序会弹出提示，建议大家采用小程序卡片作为展示方式。</li>");
document.writeln("                        <li>如需申请入驻留言板，请点击左侧菜单「入驻留言板，」或扫描「右侧二维码」</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'toolsRightBody toolsRightVideo\'>");
document.writeln("                    <div class=\'toolsRightFirst\'>");
document.writeln("                        <p class=\'toolsRightFirstP1\'>公众号名字：</p>");
document.writeln("                        <input type=\'\' name=\'\' class=\'toolsRightFirstInput1 publicInputText\'");
document.writeln("                            placeholder=\'请输入已经入驻的公众号名字\'>");
document.writeln("                        <p class=\'toolsRightFirstP4 watchVideo\'><span class=\'blink\'>点我查看最新使用视频</span></p>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'toolsRightFirst\'>");
document.writeln("                        <p class=\'toolsRightFirstP1\'>背景图片链接：</p>");
document.writeln("                        <input type=\'\' name=\'\' class=\'toolsRightFirstInput1 picInputUrl\' placeholder=\'不填则为默认背景\'>");
document.writeln("                        <p class=\'toolsRightFirstP3\'>（选填）</p>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'toolsRightFirst\'>");
document.writeln("                        <p class=\'toolsRightFirstP1\'>留言板标题：</p>");
document.writeln("                        <input type=\'\' name=\'\' class=\'toolsRightFirstInput1 titleInputText\'");
document.writeln("                            placeholder=\'建议填写即将发布的推文标题，点击【生成】生成下方路径\'>");
document.writeln("                        <p class=\'toolsRightFirstP2 newBoardBtn\'>生成</p>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'toolsRightFirst\'>");
document.writeln("                        <p class=\'toolsRightFirstP1\'>小程序路径：</p>");
document.writeln("                        <input type=\'\' name=\'\' class=\'toolsRightFirstInput1 shorUrlInput\' id=\'shorUrlInput\'");
document.writeln("                            placeholder=\'推文中插入【丁月留言】小程序后粘贴此路径\'>");
document.writeln("                        <p class=\'toolsRightFirstP2 fzBtn\'>复制</p>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    <div class=\'toolsRightCoverDrawing\'>");
document.writeln("                        <p style=\'color: #44b549;font-size: 14px;margin-top: 40px;\'>");
document.writeln("                            填写了正确的背景图片链接，在点击【生成】后才会在下方显示背景原图。</p>");
document.writeln("                        <p class=\'toolsRightCoverDrawingp1\'><img src=\'images/nopic.png\' id=\'coverImg\'></p>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    <p class=\'toolsRightThirdTitle\'>简要说明：</p>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>1、公众号名字填写已经入驻成功的公众号名字。</p>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>2、留言板标题建议填写即将发布的推文标题。</p>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>3、背景图片链接不填则为默认的图片，如需要填写，请选择长宽比为2.35:1的图片（微信推文封面图的比例），怎么获取图片链接参考<a");
document.writeln("                            href=\'http://www.xmyeditor.com/tools/cover.html\' target=\'_blank\'>采用微信封面图作为背景</a>或者<a");
document.writeln("                            href=\'http://www.nephen.cn/2019/04/04/订阅号留言板：公众号留言功能开通新思路！/#采用公众号素材图片作为背景\'");
document.writeln("                            target=\'_blank\'>采用公众号素材图片作为背景</a>，也可以在推文发布后在小程序的管理留言板上传背景图片（如下图）。</p>");
document.writeln("                    <img id=\'tu\' style=\'width: 300px; padding-top: 20px; height: auto;\' src=\'images/back.png\'>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>4、点击生成后，将小程序路径【复制到公众号文章小程序路径】处（如下图），更多请参考<a");
document.writeln("                            href=\'http://www.nephen.cn/2019/04/04/订阅号留言板：公众号留言功能开通新思路！/#二-将留言板嵌入公众号文章\'");
document.writeln("                            target=\'_blank\'>将留言板嵌入公众号文章</a>。</p>");
document.writeln("                    <img id=\'tu\' style=\'width: 300px; padding-top: 20px; height: auto;\' src=\'images/paste.png\'>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>5、另外，上图里小程序展示方式【建议选择小程序卡片】，可以参考下方图片，吸引读者点击进入留言页面。</p>");
document.writeln("                    <img id=\'tu\' style=\'width: 300px; padding-top: 20px; height: auto;\' src=\'images/msg.png\'>");
document.writeln("                    <p class=\'toolsRightCoverDrawingp2\' style=\'margin-bottom: 20px\'><a href=\'images/msg.png\'");
document.writeln("                            style=\'color: #ffffff;\' download=\'留言板封面图.png\'>下载该图片</a></p>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>6、为避免出错，请在文章发布前【务必预览下文章】，看留言板是否能正常打开！</p>");
document.writeln("                    <p class=\'toolsRightThirdTitle\'>注意：</p>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>1、必须入驻成为留言板管理员才能成功使用留言板，如还未申请入驻，请扫描下图进行申请。</p>");
document.writeln("                    <img id=\'tu\' style=\'width: 150px; padding-top: 20px; height: 150px;\' src=\'images/ewm.jpg\'>");
document.writeln("                    <p class=\'toolsRightThirdTxt\'>2、如话题比较敏感，请关闭读者互动，关闭自动精选，留言审核发现有不良言论，会被系统拉黑限制使用！</p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </section>");
document.writeln("</section>");
document.writeln("");
document.writeln("<!-- ——————————————————————网站底部信息——————————————————————————————-->");
document.writeln("");
document.writeln("<!-- 尾部 -->");
document.writeln("<div class=\'Foot\'>");
document.writeln("    <div class=\'FootBody\'>");
document.writeln("");
document.writeln("        <div class=\'Friend-link\'>");
document.writeln("            <div class=\'Friend-link-div\'>友情链接：</div>");
document.writeln("            <ul class=\'Friend-link-ul\'>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.xmyeditor.com/\' target=\'_blank\'>微信排版</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.zhichiwangluo.com\' target=\'_blank\'>H5页面制作工具</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://wewen.io\' target=\'_blank\'>公众号分析工具</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.soogif.com/\' target=\'_blank\'>GIF动图</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.tubiaoxiu.com\' target=\'_blank\'>在线图表制作</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.shenzan.com\' target=\'_blank\'>神赞</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.beetobees.com/Case/Index.html?acode=xmy\'");
document.writeln("                        target=\'_blank\'>免费H5微营销</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.msmbjp.com\' target=\'_blank\'>公众号免费增粉平台</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.juweixin.com\' target=\'_blank\'>公众号导航大全</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'https://www.gaoding.com\' target=\'_blank\'>稿定设计</a></li>");
document.writeln("                <li><a rel=\'nofollow\' href=\'http://www.xmypage.com\' target=\'_blank\'>微信页面模板</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'FootMenu\'>");
document.writeln("            <ul>");
document.writeln("                <li><a rel=\'nofollow\'>关于我们</a></li>");
document.writeln("                <li><a rel=\'nofollow\'>商务合作</a></li>");
document.writeln("                <li><a rel=\'nofollow\'>服务协议</a></li>");
document.writeln("                <li><a rel=\'nofollow\'>意见反馈</a></li>");
document.writeln("                <!-- href=\'http://www.xmyeditor.com/member/feedback/suggestadd.html\' target=\'_blank\' -->");
document.writeln("                <script");
document.writeln("                    type=\'text/javascript\'>var cnzz_protocol = ((\'https:\' == document.location.protocol) ? \' https://\' : \' http://\'); document.write(unescape(\'%3Cspan id=\'cnzz_stat_icon_1254847944\'%3E%3C/span%3E%3Cscript src=\'\' + cnzz_protocol + \'s95.cnzz.com/z_stat.php%3Fid%3D1254847944\' type=\'text/javascript\'%3E%3C/script%3E\'));</script>");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'Footerweima\'>");
document.writeln("            <div><img src=\'images/ewm.jpg\' alt=\'\' style=\'padding:2px;\'></div>");
document.writeln("            <p>扫码查看帮助</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");